// Generated by python -m scripts.export_contracts; do not edit.
export interface Actor {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
}
export interface Body_evidence_api_v1_evidence_post {
  file: string;
}
export interface CSVInput {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
  csv: string;
}
export interface CapacityInput {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
  facility_id: string;
  physical_beds?: number | null;
  operational_beds?: number | null;
  occupied_beds?: number | null;
  staff_by_role?: Record<string, number>;
  footfall?: number | null;
}
export interface ClockInput {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
  hours: number;
}
export interface ConfirmInput {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
  draft_id: string;
  observations: Array<StockInput>;
}
export interface ExtractInput {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
  evidence_id: string;
}
export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}
export interface NewSession {
  state?: "A" | "B";
  scenario?: string;
}
export interface PlanInput {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
  product?: string;
  recipient?: string;
  forecast_id?: string | null;
}
export interface ReceiptInput {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
  quantity: number;
}
export interface ReplenishmentInput {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
  batch: string;
  quantity: number;
  eta_min_days: number;
  eta_max_days: number;
}
export interface StockInput {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
  batch: string;
  quantity: number;
  mode?: "snapshot" | "receipt" | "consume";
  observed_at: string;
  reason: string;
}
export interface TransferInput {
  role?: "custodian" | "planner" | "approver" | "receiver";
  district?: "D1" | "D2";
  expected_version?: number;
  plan_id: string;
  line_index?: number;
}
export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
}
