import {useEffect,useState,type ReactNode} from 'react';
import {api} from './api';
import {people,places,steps} from './storyData';
import './guide.css';
import './deployment.css';

type Snapshot={session:any;inventory:any[];transfers:any[];audit:any[];readiness:any[]};
type Person=typeof people.reporter;
const initial={session:null,inventory:[],transfers:[],audit:[],readiness:[]};
const actor=(p:Person,version=1)=>({role:p.role,district:p.district,expected_version:version});

export function DemoExperience({advanced}:{advanced:ReactNode}){
 const [expert,setExpert]=useState(new URLSearchParams(location.search).get('workspace')==='1');
 const [data,setData]=useState<Snapshot>(initial),[loading,setLoading]=useState(false),[starting,setStarting]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [count,setCount]=useState(40),[received,setReceived]=useState(60),[plan,setPlan]=useState<any>(null),[teamOpen,setTeamOpen]=useState(false);
 const [help,setHelp]=useState(false);
 useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(''),5000);return()=>window.clearTimeout(timer)},[notice]);
 const savedPlanKey=(id:string)=>'story-plan:'+id;
 async function refresh(){
   const [session,inventory,transfers,audit,readiness]=await Promise.all(['session','inventory','transfers','audit','readiness'].map(p=>api('/api/v1/'+p)));
   const snapshot={session,inventory,transfers,audit,readiness};setData(snapshot);return snapshot;
 }
 useEffect(()=>{if(!sessionStorage.getItem('token')){setStarting(false);return}refresh().then(s=>{const saved=sessionStorage.getItem(savedPlanKey(s.session.id));if(saved)setPlan(JSON.parse(saved));}).catch(()=>setData(initial)).finally(()=>setStarting(false));},[]);
 async function perform(work:()=>Promise<void>){setLoading(true);setError('');setNotice('');try{await work()}catch(e:any){setError(friendlyError(e));}finally{setLoading(false)}}
 async function start(){await perform(async()=>{
   const s=await api('/api/v1/demo/sessions',{state:'A',scenario:'GOLDEN'});
   sessionStorage.setItem('token',s.token);sessionStorage.setItem('session_id',s.session_id);sessionStorage.removeItem('model_job');setPlan(null);setCount(40);setReceived(60);
   await refresh();setNotice('Your own practice story is ready. Start with Anitha’s morning stock count.');
 });}
 function openWorkspace(){history.replaceState(null,'','?workspace=1');setExpert(true)}
 function closeWorkspace(){history.replaceState(null,'','/');setExpert(false);if(sessionStorage.getItem('token'))refresh().catch(e=>setError(friendlyError(e)))}
 const active=data.transfers.find(t=>!['cancelled','expired'].includes(t.status));
 const reported=data.audit.some(a=>a.payload.action==='stock');
 const step=active?.status==='received'?5:active?.dispatched?4:active?.status==='approved'?3:active?2:reported?1:0;
 const person=step===0?people.reporter:step===1?people.planner:step===2?(active.approvals.includes('D1')?people.donorApprover:people.recipientApprover):step===3?people.sender:people.receiver;
 const stocks=(f:string)=>data.inventory.filter(b=>b.facility_id===f&&b.medicine_code==='MED-001').reduce((n,b)=>n+b.on_hand,0);
 const committed=active?.quantity||0;
 const shared=active?.received||0;
 const missing=active?active.dispatched-active.received:0;
 const shortfall=Math.max(0,100-stocks('A'));
 const usablePlan=plan?.payload?.lines?.length>0;
 async function compute(){await perform(async()=>{
   const result=await api('/api/v1/plans',actor(people.planner));setPlan(result);sessionStorage.setItem(savedPlanKey(data.session.id),JSON.stringify(result));await refresh();
   setNotice(result.payload.lines.length?'The available medicine has been checked. Review the recommendation below.':'No centre can safely cover this shortage. The app has not invented a delivery.');
 });}
 async function transferAction(action:string,p:Person,extra={}){await perform(async()=>{
   await api(`/api/v1/transfers/${active.id}/${action}`,{...actor(p,active.version),...extra});await refresh();
   setNotice(action==='approve'?`${p.name} has approved this transfer.`:action==='dispatch'?'Farah has recorded the box leaving Anandapur. The tablets are now marked “on the way”.':`${received} tablets have been added to Madhavapur’s medicine stock.`);
 });}
 if(expert)return <><div className="back-to-story"><button onClick={closeWorkspace}>← Back to the guided story</button><span>Detailed workspace · For exploring every feature</span></div>{advanced}</>;
 return <div className="guide-app">
   <div className="guide-disclosure"><span>Practice demo · Fictional people, places and records</span><span>Every button saves a real change inside your demo</span></div>
   <header className="guide-header"><a href="/" className="guide-logo" onClick={e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'})}}><span>+</span><div>SwasthyaSetu<small>Helping health centres help each other</small></div></a><div className="guide-header-actions"><button className="guide-text-button" onClick={()=>setHelp(!help)}>What does this do?</button><button className="guide-text-button" onClick={openWorkspace}>Detailed workspace ↗</button></div></header>
   {help&&<section className="guide-explainer"><b>A medicine shortage should not become a last-minute emergency.</b><p>One health centre may be running low while another has enough to share. SwasthyaSetu helps the team spot the gap, choose a safe source, get permission and check that the medicine actually arrived.</p><button className="guide-text-button" onClick={()=>setHelp(false)}>Got it</button></section>}
   {starting?<main className="guide-loading" aria-live="polite">Opening your practice story…</main>:!data.session?<main className="guide-welcome">
     <section><div className="guide-kicker">A DAY IN A HEALTH CENTRE</div><h1>One centre is running low.<br/><em>Another can help.</em></h1><p className="guide-intro">It’s Monday morning in Madhavapur. Anitha, the pharmacist, has counted just <b>40 paracetamol tablets</b>. The centre expects to need <b>100 this week</b>.</p><p className="guide-intro">Can the team arrange the missing 60 tablets without putting another centre at risk?</p><button className="guide-primary guide-start" disabled={loading} onClick={start}>{loading?'Preparing your story…':'Try the 3-minute story'} <span>→</span></button><p className="guide-soft">No sign-up. No knowledge of healthcare systems needed.<br/>You’ll meet each person and see exactly what they do.</p><div className="guide-preview-steps">{['Spot the shortage','Choose who can help','Follow the delivery'].map((s,i)=><div key={s}><span>{i+1}</span>{s}</div>)}</div></section>
     <section className="morning-card"><div className="morning-top"><span>MONDAY · MORNING STOCK CHECK</span><span className="guide-pill amber">Medicine running low</span></div><div className="clinic-illustration" aria-hidden="true"><div className="clinic-building"><span>+</span><b>MADHAVAPUR HEALTH CENTRE</b><div className="clinic-windows"><i/><i/><i/></div></div><div className="clinic-ground"/></div><h2>Madhavapur Health Centre</h2><p>Riverbend district · Fictional demo location</p><div className="shelf-count"><div><strong>40</strong><span>tablets on the shelf</span></div><div><strong>100</strong><span>expected need this week</span></div></div><div className="guide-shortage"><b>60 tablets needed</b><span>Let’s find a safe way to get them here.</span></div><blockquote>“I’ve counted the stock. We need help before the week gets busy.”<cite>Anitha Rao · Pharmacist · Fictional character</cite></blockquote></section>
   </main>:data.session.scenario!=='GOLDEN'?<main className="guide-loading"><h1>Let’s start with a simple story.</h1><p>Your existing practice session uses another scenario. Start the guided shortage-to-delivery story, or explore that session in the detailed workspace.</p><button disabled={loading} onClick={start}>Start the guided story</button></main>:<main className="guide-main">
     <div className="guide-page-title"><div><div className="guide-kicker">YOUR PRACTICE STORY · MADHAVAPUR</div><h1>{step===5?'The medicine has arrived.':'Help medicine reach the right place.'}</h1><p>{step===5?'The receiving team has checked the box. The records now show where every tablet is.':'Follow the team from the first stock count to a confirmed delivery.'}</p></div><button className="guide-text-button" disabled={loading} onClick={start}>Start a fresh story ↻</button></div>
     <ol className="guide-progress" aria-label="Story progress">{steps.map((s,i)=><li key={s} className={step>i?'done':step===i?'current':''}><span>{step>i?'✓':i+1}</span><div>{s}<small>{step>i?'Completed':step===i?'You are here':'Coming next'}</small></div></li>)}</ol>
     <div className="guide-layout"><section className="guide-main-column">
       <section className={'guide-action-card '+(step===5?'guide-complete':'')} aria-labelledby="current-action">
         {step<5&&<div className="acting-person"><div className="person-avatar">{person.initials}</div><div><small>FOR THIS STEP, YOU ARE HELPING</small><strong>{person.name}</strong><span>{person.title}</span></div><button className="guide-text-button" onClick={()=>setTeamOpen(!teamOpen)}>Meet the team</button></div>}
         {step===0&&<><div className="guide-kicker">STEP 1 / CHECK WHAT’S ON THE SHELF</div><h2 id="current-action">Anitha counts the medicine.</h2><p>Before anyone sends more, the team needs an up-to-date count. Anitha has found <b>4 strips of 10 tablets</b> in the cupboard.</p><div className="medicine-label"><span className="medicine-symbol" aria-hidden="true">▰</span><div><b>Paracetamol · 500 mg</b><span>Tablet · Pack of 10 · Batch SYN-01</span><small>Fictional stock record, not a treatment instruction</small></div></div><label className="guide-count-label">How many tablets did Anitha count?<div className="guide-number-input"><input aria-label="Tablets counted" type="number" min="0" max="100000" value={count} onChange={e=>setCount(Number(e.target.value))}/><span>tablets</span></div></label><p className="guide-soft">The prepared story uses 40. You can change the count and see the recommendation change.</p><button className="guide-primary" disabled={loading} onClick={()=>perform(async()=>{const b=data.inventory.find(b=>b.id==='A-MED-001');await api('/api/v1/stock-events',{...actor(people.reporter,b.version),batch:b.id,quantity:count,mode:'snapshot',observed_at:data.session.scenario_clock,reason:'Anitha’s fictional morning shelf count'});await refresh();setNotice('Anitha’s count is saved. Vikram can now look for a centre that can help.');})}>Save Anitha’s stock count →</button><div className="why-this-step"><b>Why this matters</b><p>Old stock numbers can cause the wrong decision. This count becomes the starting point for the transfer.</p></div></>}
         {step===1&&<><div className="guide-kicker">STEP 2 / FIND SOMEWHERE THAT CAN HELP</div><h2 id="current-action">Vikram looks beyond the nearest centre.</h2><p>Madhavapur has <b>{stocks('A')} tablets</b>, against the example week’s expected need of <b>100</b>. {shortfall>0?`That leaves a gap of ${shortfall} tablets.`:'There is no shortage against this week’s example requirement.'}</p><progress className="guide-need-bar" max="100" value={Math.min(100,stocks('A'))} aria-label={`${stocks('A')} of 100 tablets available`}/><div className="guide-bar-labels"><span>{stocks('A')} on the shelf</span><span>100 needed for this example week</span></div><button className="guide-primary" disabled={loading} onClick={compute}>{plan?'Check the centres again':'Find a centre that can help'} →</button>{plan&&<div className="recommendation" aria-live="polite"><span className="guide-pill">Stock checked</span><h3>{usablePlan?`${places[plan.payload.lines[0].source]?.short} can share ${plan.payload.lines[0].quantity} tablets.`:'No safe transfer is available.'}</h3><p>{usablePlan?'The calculation keeps enough medicine at the sending centre for its own patients and a small safety reserve.':'The app leaves the need open so the coordinator can arrange another supply. It does not approve an unsafe transfer.'}</p>{plan.payload.unresolved>0&&<p className="guide-inline-warning">{plan.payload.unresolved} tablets still need another source.</p>}{usablePlan&&<button className="guide-primary" disabled={loading} onClick={()=>perform(async()=>{await api('/api/v1/transfers',{...actor(people.planner),plan_id:plan.id,line_index:0});await refresh();setReceived(plan.payload.lines[0].quantity);setNotice('The tablets are set aside. The two district officers must now agree to the transfer.');})}>Request these {plan.payload.lines[0].quantity} tablets →</button>}</div>}<div className="why-this-step"><b>What does “can share” mean?</b><p>Medicine left after covering that centre’s expected need and safety reserve. A nearby centre is not automatically the safest choice.</p></div></>}
         {step===2&&<><div className="guide-kicker">STEP 3 / GET BOTH TEAMS’ PERMISSION</div><h2 id="current-action">{person.name} reviews the request.</h2><p>{person.task} The request is for <b>{active.quantity} tablets</b> from <b>{places[active.source]?.short}</b> to <b>{places[active.destination]?.short}</b>.</p><div className="approval-pair">{[people.recipientApprover,people.donorApprover].map(p=><div key={p.name} className={active.approvals.includes(p.district)?'signed':''}><span>{active.approvals.includes(p.district)?'✓':'○'}</span><b>{p.name}</b><small>{p.title}</small><strong>{active.approvals.includes(p.district)?'Approved in this demo':'Waiting for approval'}</strong></div>)}</div><button className="guide-primary" disabled={loading} onClick={()=>transferAction('approve',person)}>Approve as {person.name} →</button><div className="why-this-step"><b>Why two approvals?</b><p>The team requesting medicine and the team sending it both need to agree. The box cannot be sent until both approvals are recorded.</p></div></>}
         {step===3&&<><div className="guide-kicker">STEP 4 / PACK AND SEND</div><h2 id="current-action">Farah prepares the medicine box.</h2><p>Both district officers have agreed. Farah checks the batch, packs <b>{active.quantity} tablets</b>, and hands the box to the delivery team in this simulation.</p><div className="parcel-card"><span aria-hidden="true">▣</span><div><b>MADHAVAPUR HEALTH CENTRE</b><p>{active.quantity} paracetamol 500 mg tablets<br/>From Anandapur · Batch SYN-01</p><small>Expected journey: 2 demo days · Illustrative route</small></div></div><button className="guide-primary" disabled={loading} onClick={()=>transferAction('dispatch',people.sender)}>Record the box leaving Anandapur →</button><div className="why-this-step"><b>What changes when it leaves?</b><p>The medicine is removed from Anandapur’s shelf count and shown as “on the way”. It will only be added at Madhavapur after Anitha checks the delivery.</p></div></>}
         {step===4&&<><div className="guide-kicker">STEP 5 / CHECK THE DELIVERY</div><h2 id="current-action">{active.received>0?'Anitha checks the remaining tablets.':'Fast-forward the story: the box arrives.'}</h2><p>{active.received>0?`${active.received} tablets have been confirmed. ${missing} are still marked as not yet received.`:'In this practice story, you now act as the receiving pharmacist. There is no live vehicle tracking or physical shipment.'}</p><div className="delivery-route"><span>{places[active.source]?.short}</span><div><i className="moving-parcel">▣</i></div><span>{places[active.destination]?.short}</span></div><label className="guide-count-label">How many tablets arrived?<div className="guide-number-input"><input aria-label="Tablets received" type="number" min="1" max={missing} value={received} onChange={e=>setReceived(Number(e.target.value))}/><span>of {missing} still expected</span></div></label><div className="guide-quick-actions"><button disabled={loading} className="guide-text-button" onClick={()=>setReceived(missing)}>All {missing} arrived</button>{missing>20&&<button disabled={loading} className="guide-text-button" onClick={()=>setReceived(20)}>Try a partial delivery: only 20 arrived</button>}</div><button className="guide-primary" disabled={loading||received<1||received>missing} onClick={()=>transferAction('receive',people.receiver,{quantity:received})}>Confirm {received} tablets received →</button><div className="why-this-step"><b>Why count again?</b><p>A delivery is not complete just because somebody sent it. If tablets are missing, the app keeps the remaining amount open.</p></div></>}
         {step===5&&<><div className="completion-check">✓</div><div className="guide-kicker">STORY COMPLETE</div><h2 id="current-action">{shared} tablets received and accounted for.</h2><p>Madhavapur now has <b>{stocks('A')} tablets</b>. Anandapur has <b>{stocks(active.source)} left</b>. {shortfall===0?'The example week’s medicine gap is covered.':`${shortfall} tablets are still needed against the example week’s requirement.`}</p><div className="completion-stats"><div><strong>{shared}</strong><span>tablets delivered in the demo</span></div><div><strong>{active.dispatched-active.received}</strong><span>tablets still unaccounted for</span></div><div><strong>2</strong><span>district approvals recorded</span></div></div><p>This is what SwasthyaSetu connects: an accurate stock count, a safe sharing decision, permission from both teams, and proof of receipt.</p><button className="guide-primary" onClick={openWorkspace}>Explore the full app →</button><button className="guide-text-button" disabled={loading} onClick={start}>Run the story again</button></>}
       </section>
       {teamOpen&&<section className="guide-team"><div className="guide-section-heading"><h2>Who does what?</h2><button className="guide-text-button" onClick={()=>setTeamOpen(false)}>Close</button></div><p>These are fictional team members. In a real service, different authorized people would sign in. Here, you try each person’s job in turn.</p><div>{[people.reporter,people.planner,people.recipientApprover,people.donorApprover,people.sender].map(p=><article key={p.name}><span className="person-avatar">{p.initials}</span><div><h3>{p.name}</h3><b>{p.title}</b><p>{p.task}</p></div></article>)}</div></section>}
       <section className="guide-centres"><div className="guide-section-heading"><div><div className="guide-kicker">THE THREE CENTRES IN THIS STORY</div><h2>Who has medicine, and who needs it?</h2></div><span className="guide-pill">Saved demo records</span></div><div className="centre-cards">{['A','B','C'].map(f=>{const onShelf=stocks(f),need=f==='C'?60:100,reserve=f==='B'?20:f==='C'?30:0;const cap=data.readiness.find(c=>c.payload.facility_id===f)?.payload;return <article key={f} className={f==='A'?'recipient-centre':''}><div className="centre-icon">+</div><h3>{places[f].short}</h3><span>{places[f].district}</span><strong>{onShelf}<small>tablets on the shelf</small></strong><dl><div><dt>Example week’s need</dt><dd>{need}</dd></div>{reserve>0&&<div><dt>Safety reserve</dt><dd>{reserve}</dd></div>}<div><dt>Visitors in sample day</dt><dd>{cap?.footfall??'—'}</dd></div></dl><p>{f==='A'?(shortfall>0?`Needs ${shortfall} more tablets.`:'This week’s example need is covered.'):f==='B'?'Nearby, but all 120 tablets are needed for its own patients and reserve.':active?.dispatched?'Its remaining stock stays at the centre.':`Before this transfer, ${Math.max(0,onShelf-need-reserve)} tablets can be shared.`}</p></article>})}</div><p className="guide-footnote">The week’s demand and safety reserves are prepared example values for this story. Other scenarios in the detailed workspace run the forecasting model. All counts above come from your saved demo.</p></section>
     </section><aside className="guide-side"><section className="guide-status"><div className="guide-kicker">WHERE ARE THE TABLETS NOW?</div><h2>{step===5?'Delivery confirmed':step>=4?'On the way':step>=2?'Set aside for Madhavapur':'Waiting for a decision'}</h2><div className="medicine-journey"><div className={step>=3?'passed':''}><span>1</span><p>Anandapur shelf<small>{stocks('C')} tablets remain here</small></p></div><div className={step>=4?'passed':''}><span>2</span><p>On the way<small>{active?active.dispatched-active.received:0} tablets not yet received</small></p></div><div className={step===5?'passed':''}><span>3</span><p>Madhavapur shelf<small>{stocks('A')} tablets available here</small></p></div></div>{committed>0&&<p className="guide-soft">Transfer requested: {committed} tablets<br/>Confirmed at destination: {shared} tablets</p>}</section><section className="guide-activity"><div className="guide-kicker">STORY SO FAR</div><h2>The team’s activity</h2><ol><li><span className="activity-dot"/><div><b>The practice day begins</b><p>40 tablets at Madhavapur, 120 at Sevanagar and 150 at Anandapur.</p><small>Prepared fictional opening record</small></div></li>{reported&&<li><span className="activity-dot"/><div><b>Anitha’s stock count saved</b><p>The team has a confirmed starting count.</p><small>Recorded by your action</small></div></li>}{active&&<li><span className="activity-dot"/><div><b>Vikram requested {active.quantity} tablets</b><p>Anandapur’s own medicine needs were protected.</p><small>Calculated and saved in the app</small></div></li>}{active?.approvals.map((d:string)=><li key={d}><span className="activity-dot"/><div><b>{d==='D1'?'Dr Kavya Rao':'Dr Imran Ali'} approved</b><p>{d==='D1'?'Receiving team':'Sending team'} agreed to the request.</p><small>Recorded approval</small></div></li>)}{active?.dispatched>0&&<li><span className="activity-dot"/><div><b>Farah recorded the box leaving</b><p>{active.dispatched} tablets moved off the sending centre’s shelf.</p><small>Simulated dispatch, saved stock movement</small></div></li>}{shared>0&&<li><span className="activity-dot"/><div><b>Anitha confirmed {shared} tablets</b><p>{missing>0?`${missing} tablets remain unconfirmed.`:'The requested delivery is fully received.'}</p><small>Saved receipt</small></div></li>}</ol></section><button className="guide-team-link" onClick={()=>setTeamOpen(!teamOpen)}>Who are these people? <span>→</span></button></aside></div>
   </main>}
   {(error||notice||loading)&&<div className={'guide-message '+(error?'is-error':'')} role={error?'alert':'status'}><span>{loading?'Saving this step…':error||notice}</span>{!loading&&<button aria-label="Dismiss message" onClick={()=>{setError('');setNotice('')}}>×</button>}</div>}
   <footer className="guide-footer"><b>SwasthyaSetu</b><span>A working practice demo. People, demand figures, locations and deliveries are fictional.</span><button className="guide-text-button" onClick={openWorkspace}>See the detailed workspace</button></footer>
 </div>;
}

function friendlyError(e:any){
 if(e.code==='VERSION_CONFLICT'||e.code==='STALE_PLAN')return 'The stock changed after this recommendation. Refresh the page and check the centres again.';
 if(e.code==='SESSION_EXPIRED'||e.code==='UNAUTHORISED')return 'This practice session has expired. Start a fresh story.';
 if(e.code==='QUOTA_EXCEEDED'||e.code==='SANDBOX_CAPACITY')return 'The free demo is busy or this session has reached its limit. Please try again later.';
 return e.message||'This step could not be saved. Please try again.';
}
