import {useEffect,useState} from 'react';
import {api} from './api';
export function Replenishments({actor,session,onChange}:{actor:any;session:any;onChange:()=>Promise<void>}){
 const [rows,setRows]=useState<any[]>([]),[message,setMessage]=useState(''),[quantity,setQuantity]=useState(50),[busy,setBusy]=useState(false);
 const load=async()=>setRows(await api('/api/v1/replenishments'));
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[session.id,session.version]);
 async function run(fn:()=>Promise<unknown>){setBusy(true);try{await fn();await load();await onChange();setMessage('Synthetic supply updated. Refresh analysis to include the change.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="card"><div className="eyebrow">INCOMING SUPPLY / SYNTHETIC ETA</div><h2>Replenishments</h2><p>Scheduled deliveries affect forecast scenarios; they do not become stock until a custodian confirms receipt. Late supply does not erase an earlier shortage.</p><div className="formrow"><label>Tablets for A<input type="number" min="1" value={quantity} onChange={e=>setQuantity(+e.target.value)}/></label><button disabled={busy} onClick={()=>run(async()=>{const inv=await api('/api/v1/inventory');return api('/api/v1/replenishments',{...actor,expected_version:inv.find((b:any)=>b.id==='A-MED-001').version,batch:'A-MED-001',quantity,eta_min_days:1,eta_max_days:2})})}>Schedule 1–2 day supply</button><button className="secondary" disabled={busy} onClick={()=>run(()=>api('/api/v1/demo/clock',{...actor,expected_version:session.version,hours:24}))}>Advance scenario 24 hours</button></div>{rows.map(r=><div className="result" key={r.id}><b>{r.payload.quantity} {r.payload.product} base units → {r.payload.facility_id}</b><p>{r.payload.status} · ETA {r.payload.eta_min.slice(0,10)} – {r.payload.eta_max.slice(0,10)}</p>{r.payload.status==='scheduled'&&<button disabled={busy} onClick={()=>run(()=>api(`/api/v1/replenishments/${r.id}/receive`,{...actor,expected_version:r.version}))}>Confirm arrival as custodian</button>}</div>)}{message&&<p role="status">{message}</p>}</section>
}
