import json
from pathlib import Path
from services.api.main import app
def main():
    schema=app.openapi(); Path('docs/openapi.json').write_text(json.dumps(schema,indent=2))
    names=sorted(schema['components']['schemas'])
    # Generated type aliases retain required/optional and basic OpenAPI primitives.
    def ts(s):
        if '$ref' in s:return s['$ref'].split('/')[-1]
        if 'enum' in s:return ' | '.join(json.dumps(x) for x in s['enum'])
        if 'anyOf' in s:return ' | '.join(ts(x) for x in s['anyOf'])
        kind=s.get('type')
        if kind=='array':return f'Array<{ts(s["items"])}>'
        if kind=='object':return 'Record<string, '+ts(s.get('additionalProperties',{}))+'>'
        return {'integer':'number','number':'number','string':'string','boolean':'boolean','null':'null'}.get(kind,'unknown')
    lines=['// Generated by python -m scripts.export_contracts; do not edit.']
    for name in names:
        item=schema['components']['schemas'][name];required=item.get('required',[])
        lines.append(f'export interface {name} '+'{')
        for k,v in item.get('properties',{}).items():lines.append(f'  {k}{"" if k in required else "?"}: {ts(v)};')
        lines.append('}')
    Path('apps/web/src/contracts.ts').write_text('\n'.join(lines)+'\n')
    print('OpenAPI and TypeScript contracts generated')
if __name__=='__main__':main()
